{% set edition = "2021" %}
{% set version = "20210325" %}

package:
  name: texlive-split
  version: {{ version }}

source:
  - url: ftp://tug.org/texlive/historic/{{ edition }}/texlive-{{ version }}-source.tar.xz
    sha256: 7aefd96608d72061970f2d73f275be5648ea8ae815af073016d3106acc0d584b
  - url: ftp://tug.org/texlive/historic/{{ edition }}/texlive-{{ version }}-extra.tar.xz
    sha256: 46a3f385d0b30893eec6b39352135d2929ee19a0a81df2441bfcaa9f6c78339c
    folder: extra
  - url: ftp://tug.org/texlive/historic/{{ edition }}/texlive-{{ version }}-texmf.tar.xz
    sha256: ff12d436c23e99fb30aad55924266104356847eb0238c193e839c150d9670f1c
    folder: texmf

build:
  number: 7
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libxrender-devel') }}  # [linux]
    - {{ cdt('libxext-devel') }}     # [linux]
    - {{ cdt('libxau-devel') }}      # [linux]
    - pkg-config
    - texinfo
    - make
    - sed
    - patch
  host:
    # glib is required for cairo's pkg-config check
    - glib
    - cairo
    - freetype
    - fontconfig
    - gmp
    - harfbuzz >=1.8.*
    - graphite2
    - icu
    - libpng
    - mpfr
    - pixman
    - perl
    - poppler
    - zlib
  run:
    - {{ pin_subpackage('texlive-core', exact=True) }}
    - {{ pin_subpackage('texlive-fonts', exact=True) }}
    - {{ pin_subpackage('texlive-texmf', exact=True) }}

outputs:
  - name: texlive-core
    script: install.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ cdt('libxrender-devel') }}  # [linux]
        - {{ cdt('libxext-devel') }}     # [linux]
        - {{ cdt('libxau-devel') }}      # [linux]
        - pkg-config
        - texinfo
        - make
        - sed
        - patch
      host:
        # glib is required for cairo's pkg-config check
        - glib
        - cairo
        - freetype
        - fontconfig
        - gmp
        - harfbuzz >=1.8.*
        - graphite2
        - icu
        - libpng
        - mpfr
        - pixman
        - perl
        - poppler
        - zlib
      run:
        - fontconfig

    test:
      commands:
        - pdftex --version
        - bibtex --version
        # Test the symlinks.
        - pdflatex --version
        - latex --version

  - name: texlive-texmf
    script: install_texmf.sh
    requirements:
        run:
            - {{ pin_subpackage('texlive-core', exact=True) }}

  - name: texlive-fonts
    script: install_fonts.sh
    requirements:
        run:
            - {{ pin_subpackage('texlive-core', exact=True) }}

about:
  home: https://www.tug.org/texlive/
  license: GPL-2.0-or-later AND GPL-2.0-only AND GPL-3.0-only AND LPPL-1.3c AND LPPL-1.0 AND Artistic-1.0 AND Apache-2.0 AND MIT AND BSD-3-Clause
  # See https://www.tug.org/texlive/LICENSE.TL
  license_file: LICENSE.TL
  summary: 'An easy way to get up and running with the TeX document production system.'

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - xhochy
